<h2>Taller 4: Programación dinamica</h2>

<p>1.LCS</p>

In [1]:
import math
import time
import random as rnd
import numpy as np

<p>Se utliza el algortitmo que se implemento en clase.</p>

In [2]:
global C

def lcs(X,Y):
    global C
    C = np.ones((len(X)+1,len(Y)+1))*-1
    lcs3(X,Y,len(X),len(Y))
    return C[len(X)-1,len(Y)-1], C
    

def lcs3(x,y,i,j):
    global C
    if C[i,j] == -1:
        if i == 0 or j == 0:
            C[i,j] = 0
        else:
            if x[i-1]==y[j-1]:
                C[i,j] = lcs3(x,y,i-1,j-1)+1
            else:
                C[i,j] = max(lcs3(x,y,i-1,j),lcs3(x,y,i,j-1))
                
    return C[i,j]

In [3]:
len_lcs, lcs_mat = lcs('ABC','AWBDC')

In [4]:
print (lcs_mat)

[[ 0. -1.  0.  0.  0. -1.]
 [-1.  1.  1.  1.  1. -1.]
 [-1. -1. -1.  2.  2. -1.]
 [-1. -1. -1. -1. -1.  3.]]


<h3>El primer punto:</h3>

In [5]:
global C
def imprimirLCS(X,Y, i,j, vec):
    global C
    if j==0 or i==0:
        if X[i]==Y[j]:
            vec.append(X[i])
        return vec
    else:
        if X[i]==Y[j]:
            vec.append(X[i]) 
        izq= C[i-1,j]
        der= C[i,j-1]
        dia= C[i-1,j-1]
        if dia >= izq and dia >=der:
            return imprimirLCS(X,Y,i-1,j-1,vec)
        elif izq>= der and izq >= dia:
            return imprimirLCS(X,Y,i-1,j,vec)
        elif der >= izq and der >= dia:
            return imprimirLCS(X,Y,i,j-1,vec)

In [6]:
a=len(lcs_mat)
vec = list()
pepe=imprimirLCS('ABC','AWBDC',2, 4,vec)
print(pepe)

['C', 'B', 'A']


<i>Para el problema de la varilla</i>
<p>Reconstruir el problema de la varilla</p>

In [7]:
def memo_cut_rodBU(p,n):
    r = [0] * (n+1)
    r[0] = 0
    for j in range(1,n+1):
        q = float('-inf')
        for i in range(1,j+1):            
            q = max(q, p[i-1]+r[j-i])
        r[j] = q
        print (r[j])
    return r[n]

In [8]:
p = [1,5,8,9,10,17,17,20,24,30]
sol = memo_cut_rodBU(p,8)
print (sol)   

1
5
8
10
13
17
18
22
22


<p><i>Para la distacia entre dos cadenas se uso la siguiente implementación</i></p>

In [9]:
def iniciaizarMatrix(m,n):
    di= np.zeros([m,n])
    return di

In [10]:
def edit(m,n,x,y):
    operacion1=0
    operacionRemplazar=0
    operacionInsertar=0
    operacionEliminar=0
    minimo=1000000.0
    di=iniciaizarMatrix(m+1,n+1)
    for i in range (0,n+1):
        di[0][i]=i *3
    for j in range (0,m+1):
        di[j][0]=j *2
    for i in range (0,m+1):
        for j in range (0, n+1):
            if (i==0 and j==0):
                aux=0 
            else:
                minimo = 10000000000.0;#se inicializa en un numero muy grande para poder minimizar
                if i > 0 and j>0 and x[i-1]==y[j-1]:
                    operacion1= di[i-1,j-1]
                    minimo=min(operacion1,minimo)
                if i >0 and j>0:
                    operacionRemplazar = di[i-1,j-1] + 1
                    minimo=min(operacionRemplazar,minimo)
                if i> 0:
                    operacionInsertar = di[i-1,j] +1
                    minimo=min(operacionInsertar,minimo)
                if j>0:
                    operacionEliminar = di[i,j-1] +1
                    minimo=min(operacionEliminar,minimo)
                di[i][j]=minimo
    return di[m][n]

In [11]:
y= "hola"
x= "holo"
m=len(x)
n= len(y)
a=edit(m,n,x,y)
print(a)

1.0


<p>Para el problema del rio se realizo la siguiente implementación</p>


Floyd warshall implementado por https://github.com/cy94/floyd-warshall

In [17]:
def floyd_warshall(graph):
    V = len(graph)
    for k in range(V):
        for i in range(V):
            for j in range(V):
                graph[i][j] = min(graph[i][j],graph[i][k]+ graph[k][j])
    for i in range(V):
        print (graph[i])

con la implementación nos da la respuesta que estamos para determinar el menor costo en cualquier grafo