<h1>Taller 2</h1>

<p>La precondición de la matrices es que ambas sean de tamaño nxn</p>

In [7]:
import numpy as np
from random import *

In [11]:
temp=[]
B=[]
temp=np.random.random((3, 3))
B=np.random.random((3, 3))

In [17]:
print(temp)
print(B)

[[ 0.08587797  0.00871025  0.7182674 ]
 [ 0.48268815  0.91229352  0.17083082]
 [ 0.80605935  0.50200952  0.24037981]]
[[ 0.32543007  0.93255057  0.58309377]
 [ 0.51313093  0.50267881  0.25783195]
 [ 0.37762284  0.95091521  0.51882564]]


In [33]:
def intialize(A):
    for i in range(0,len(A)):
        for j in range (0, len(A)):
            A.append(0)

In [69]:
def multiplyMatriz(A,B):
    tam=len(A)
    suma=np.zeros((tam, tam))
    for i in range(0, tam):
        for j in range(0, tam):
            aux=0;
            for k in range(0, tam):
                print()
                aux = A[i][k]*B[k][j] +aux
            print(i, " ", j, " ", aux)
            suma[i][j]=aux
    return suma

In [73]:
A=([[1,2,3],[1,2,3],[1,2,3]])
B=([[2,3,4],[2,3,4],[2,3,4]])
suma=multiplyMatriz(A,B)
print(suma)

0   0   12
0   1   18
0   2   24
1   0   12
1   1   18
1   2   24
2   0   12
2   1   18
2   2   24
[[ 12.  18.  24.]
 [ 12.  18.  24.]
 [ 12.  18.  24.]]


<p>Como se puede observar la suma de matrices nos aseguran la suma de una matriz de nxn</p>

In [22]:
def functionImpar(A):
    tam=len(A)
    for i in range (0,tam):
        A[i].append(0)
        A.append(0)

In [ ]:
def sumaMatrices(A,B):
    tam = len(A)
    C=[]
    intialize(C)
    for i in range(0, tam):
        for j in range (0, tam):
            C[i][j] = A[i][j] + B[i][j]
    return C

In [1]:
def divideAndConquer(A,B, hi, lo, izq, der):
    n=len(A)
    if(n==1):
        matriz = sumaMatriz(A,B)
    else:
        part1 =divideAndConquer(A,B,hi,lo/2,izq, der/2)
        parte2 =divideAndConquer(A,B,hi,lo/2,(der/2)+1, der)
        parte3 =divideAndConquer(A,B,(lo/2)+1,lo,izq, der/2)
        parte4 =divideAndConquer(A,B,(lo/2)+1,lo,(der/2)+1, der)
        c1= suma(parte1,parte2)
        C=[]
        intialize(C)
        for i in range(0, tam):
            for j in range (0, tam):
                C[i][j] = A[i][j] + B[i][j]

In [23]:
A=([[1,2,3],[1,2,3],[1,2,3]])
B=([[2,3,4],[2,3,4],[2,3,4]])
functionImpar(A)
print(A)

[[1, 2, 3, 0], [1, 2, 3, 0], [1, 2, 3, 0], 0, 0, 0]


In [ ]:
def strassen(A,B)